config/routes.rb
# Plugin's routes
# See: http://guides.rubyonrails.org/routing.html
resources :groups do
  member do
    get 'autocomplete_for_owner'
  end
end
get 'groups/:id/owners/new', :to => 'groups#new_owners', :id => /\d+/, :as => 'new_group_owners'
match 'groups/:id/owners', :controller => 'groups', :action => 'add_owners', :id => /\d+/, :via => :post, :as => 'group_owners'
match 'groups/:id/owners/:user_id', :controller => 'groups', :action => 'remove_owner', :id => /\d+/, :via => :delete, :as => 'group_owner'

app/models/group_owner.rb
class GroupOwner < ActiveRecord::Base
  unloadable
  belongs_to :user
  belongs_to :group
end

app/views/groups/_auto_register_url.html.erb
<%= labelled_form_for @group, :url => group_path(@group) do |f| %>
    <%= error_messages_for @group %>

    <div class="box tabular">
      <p><%= f.text_field :auto_register_url, :size => 80,
                          :disabled => !@group.safe_attribute?('auto_register_url')  %></p>

    </div>
    <%= submit_tag l(:button_save) %>
<% end %>

app/views/groups/_new_owners_form.html.erb
<fieldset class="box">
  <legend><%= label_tag "user_search", l(:label_user_search) %></legend>
  <p><%= text_field_tag 'user_search', nil %></p>
  <%= javascript_tag "observeSearchfield('user_search', null, '#{ escape_javascript autocomplete_for_owner_group_path(@group) }')" %>

  <div id="owners">
    <%= render_principals_for_new_group_owners(@group) %>
  </div>
</fieldset>

app/views/groups/_new_owners_modal.html.erb
<h3 class="title"><%= l(:label_user_owner) %></h3>

<%= form_for(@group, :url => group_owners_path(@group), :remote => true, :method => :post) do |f| %>
    <%= render :partial => 'new_owners_form' %>
    <p class="buttons">
      <%= submit_tag l(:button_add) %>
      <%= submit_tag l(:button_cancel), :name => nil, :onclick => "hideModal(this);", :type => 'button' %>
    </p>
<% end %>

app/views/groups/_new_users_form.html.erb
<%= javascript_include_tag 'group_owner.js', plugin: 'redmine_group_owners' %>
<fieldset class="box">
  <legend><%= label_tag "user_search", l(:label_user_search) %></legend>
  <p>
    <label><%= l(:label_select_group) %>:</label>
    <%= select_tag 'available_groups', options_for_select((User.current.available_groups - [@group]).collect{|group| [group.name, group.id]}), include_blank: true %>
   </p>
  <p><%= text_field_tag 'user_search', nil %></p>
  <%= javascript_tag "observeSearchfieldGroups('user_search', null, '#{ escape_javascript autocomplete_for_user_group_path(@group) }')" %>
  <%= javascript_tag "observeDropdownGroups('available_groups', null, '#{ escape_javascript autocomplete_for_user_group_path(@group) }')" %>

  <div id="users">
    <%= render_principals_for_new_group_users(@group) %>
  </div>
</fieldset>

app/views/groups/_owners.html.erb
<p><%= link_to l(:label_user_owner), new_group_owners_path(@group), :remote => true, :class => "icon icon-add" %></p>

<% if @group.owners.any? %>
  <table class="list users">
    <thead><tr>
      <th><%= l(:label_owner) %></th>
      <th style="width:15%"></th>
    </tr></thead>
    <tbody>
    <% @group.owners.sort.each do |user| %>
        <tr id="owner-<%= user.id %>" class="<%= cycle 'odd', 'even' %>">
          <td class="name"><%= link_to_user user %></td>
          <td class="buttons">
            <%= delete_link group_owner_path(@group, :user_id => user), :remote => true %>
          </td>
        </tr>
    <% end %>
    </tbody>
  </table>
<% else %>
  <p class="nodata"><%= l(:label_no_data) %></p>
<% end %>

app/views/groups/add_owners.js.erb
hideModal();
$('#tab-content-owners').html('<%= escape_javascript(render :partial => 'groups/owners') %>');
<% @users.each do |user| %>
  $('#owner-<%= user.id %>').effect("highlight");
<% end %>

app/views/groups/autocomplete_for_owner.js.erb
$('#owners').html('<%= escape_javascript(render_principals_for_new_group_owners(@group)) %>');

app/views/groups/index.html.erb
<div class="contextual">
<%= link_to l(:label_group_new), new_group_path, :class => 'icon icon-add' %>
</div>

<%= title l(:label_group_plural) %>
<% if @groups.any? %>
<table class="list groups">
  <thead><tr>
  <th><%=l(:label_group)%></th>
  <th><%=l(:label_user_plural)%></th>
  <%- if User.current.admin?%>
    <th></th>
  <%- end %>
  </tr></thead>
  <tbody>
<% @groups.each do |group| %>
  <tr id="group-<%= group.id %>" class="<%= cycle 'odd', 'even' %> <%= "builtin" if group.builtin? %>">
    <td class="name"><%= link_to h(group), edit_group_path(group) %></td>
    <td class="user_count"><%= (@user_count_by_group_id[group.id] || 0) unless group.builtin? %></td>
    <%- if User.current.admin?%>
        <td class="buttons"><%= delete_link group unless group.builtin?%></td>
    <%- end %>
  </tr>
<% end %>
  </tbody>
</table>
<% else %>
<p class="nodata"><%= l(:label_no_data) %></p>
<% end %>

app/views/groups/new_owners.js.erb
$('#ajax-modal').html('<%= escape_javascript(render :partial => 'groups/new_owners_modal') %>');
showModal('ajax-modal', '700px');

app/views/groups/remove_owner.js.erb
$('#tab-content-owners').html('<%= escape_javascript(render :partial => 'groups/owners') %>');